routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::redirect('/', '/project');

Route::resources([
    'project' => 'App\Http\Controllers\ProjectController',
]);

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class Client
 *
 * @property int $id
 * @property string $name
 * @property string $created_at
 * @property string $updated_at
 *
 * @package App\Models
 */
class Client extends Model
{
    use HasFactory;

    protected $guarded = [];
}

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Project
 *
 * @property int $id
 * @property string $title
 * @property int $offer
 * @property string $company
 * @property string $client
 * @property string $status
 * @property string $description
 * @property string $created_at
 * @property string $updated_at
 *
 * @package App\Models
 */
class Project extends Model
{
    public const STATUS_CANCELLED = 'cancelled';
    public const STATUS_COMPLETED = 'completed';
    public const STATUS_ACTIVE = 'active';

    protected $guarded = [];

    /**
     * Получаем массив статусов
     *
     * @return string[]
     */
    public static function getStatusList(): array
    {
        return [
            self::STATUS_ACTIVE => 'Активен',
            self::STATUS_COMPLETED => 'Завершен',
            self::STATUS_CANCELLED => 'Отменен',
        ];
    }

    /**
     * Получаем статус по его коду
     *
     * @param $status
     * @return string
     */
    public static function getStatus($status): string
    {
        $data = [
            self::STATUS_ACTIVE => 'Активен',
            self::STATUS_COMPLETED => 'Завершен',
            self::STATUS_CANCELLED => 'Отменен',
        ];

        return $data[$status];
    }

    /**
     * @return bool
     */
    public function isActive(): bool
    {
        return $this->status === self::STATUS_ACTIVE;
    }

    /**
     * @return bool
     */
    public function isCompleted(): bool
    {
        return $this->status === self::STATUS_COMPLETED;
    }

    /**
     * @return bool
     */
    public function isCancelled(): bool
    {
        return $this->status === self::STATUS_CANCELLED;
    }

    /**
     * @return string
     */
    public function getBudgetFormat(): string
    {
        return number_format($this->offer, '0', '.', ' ') . ' р.';
    }

    public function getClient()
    {
        return $this->hasOne(Client::class, 'id', 'client');
    }

    public function getClientFormat()
    {
        $client = $this->getClient()->first()->toArray();

        return $client['name'] . ' [' . $client['id'] . ']';
    }

    public function getClientNoFormat()
    {
        $client = $this->getClient()->first()->toArray();

        return $client['name'];
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Api/ClientController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Client;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function getClientsByName(Request $request)
    {
        $filter = $request->input('client');

        $clients = Client::orderBy('id')
            ->when(!empty($value = $filter), function($query) use ($value) {
                $query->where('name', 'like', '%' . $value . '%');
            })
            ->paginate(5);

        if ($clients->count()) {
            return response()->json([
                'status' => Response::HTTP_OK,
                'data' => $clients->all(),
            ], Response::HTTP_OK);
        }

        return response()->json([
            'status' => Response::HTTP_NOT_FOUND,
            'message' => 'Clients not found',
            'errors' => [],
        ], Response::HTTP_NOT_FOUND);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Models\Project;
use App\Http\Requests\Project\ProjectRequest;
use Illuminate\Http\Request;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $filter = $request->input('projects_search');

        $projects = Project::orderBy('id')
            ->when(!empty($value = $filter), function($query) use ($value) {
                $query->where('title', 'like', '%' . $value . '%');
            })
            ->paginate(20);

        return view('index', compact('projects', 'filter'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $status = Project::getStatusList();

        return view('create', compact('status'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ProjectRequest $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(ProjectRequest $request)
    {
        $project = Project::create($request->validated());

        if (isset($request['save'])) {
            return  redirect(route('project.index'));
        }

        return  redirect(route('project.edit', $project));
    }

    /**
     * Display the specified resource.
     *
     * @param Project $project
     * @return string
     */
    public function show(Project $project)
    {
        $status = Project::getStatusList();

        return view('show', compact('project', 'status'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Project $project
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Project $project)
    {
        $status = Project::getStatusList();

        return view('edit', compact('project', 'status'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ProjectRequest $request
     * @param Project $project
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(ProjectRequest $request, Project $project)
    {
        $project->update($request->validated());

        if (isset($request['save'])) {
            return  redirect(route('project.index'));
        }

        return  redirect(route('project.edit', $project));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Project $project
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Exception
     */
    public function destroy(Project $project)
    {
        $project->delete();

        return redirect(route('project.index'));
    }
}

resources/views/create.blade.php
@extends ('layouts.app')

@section ('title', 'Создать проект')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="projects">
        <div class="projects-content">
            <div class="projects-content_header">
                <h1>Создание проекта</h1>
            </div>

            <div class="projects-content-block">
                <form method="post" action="{{ route('project.store') }}" class="pt-3">
                    @csrf

                    <div class="form-group row">
                        <label for="status" class="col_form-label">
                            Статус
                        </label>

                        <select class="form-control" id="status" name="status">
                            @foreach ($status as $key => $value)
                                <option value="{{$key}}">
                                    {{ $value }}
                                </option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group row">
                        <label for="title" class="col_form-label">
                            Название проекта*
                        </label>

                        <input type="text" name="title" class="form-control" id="title" placeholder="example.ru" required>
                    </div>

                    <div class="form-group row">
                        <label for="offer" class="col_form-label">
                            Бюджет
                        </label>

                        <input type="text" name="offer" class="form-control" id="offer" placeholder="100 000">
                    </div>

                    <div class="form-group row">
                        <label for="client" class="col_form-label">
                            Клиент
                        </label>

                        <input type="text" name="client" class="form-control" id="client" placeholder="ООО 'Рога и Копыта'" value="" autocomplete="off">

                        <div id="client-list" class="client__list"></div>
                    </div>

                    <div class="form-group row">
                        <label for="description" class="col_form-label">
                            Описание
                        </label>

                        <textarea name="description" class="form-control __textarea" id="description" rows="4"></textarea>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" name="save" class="btn btn-alt-primary">
                                Добавить
                            </button>

                            <button type="submit" name="apply" class="btn btn-alt-success">
                                Применить
                            </button>

                            <a class="btn btn-alt-danger" href="{{ route('project.index') }}">
                                Отменить
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/edit.blade.php
@extends ('layouts.app')

@section ('title', 'Редактирование проекта -' . $project->title)

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="projects">
        <div class="projects-content">
            <div class="projects-content_header">
                <h1>Редактирование проекта</h1>
            </div>

            <div class="projects-content-block">
                <form method="post" action="{{ route('project.update', $project) }}" class="pt-3">
                    @csrf
                    @method('PUT')

                    <div class="form-group row">
                        <label for="status" class="col_form-label">
                            Статус
                        </label>

                        <select class="form-control" id="status" name="status">
                            @foreach ($status as $key => $value)
                                <option @if ($key == $project->status) selected @endif value="{{$key}}" >
                                    {{ $value }}
                                </option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group row">
                        <label for="title" class="col_form-label">
                            Название проекта*
                        </label>

                        <input type="text" name="title" class="form-control" id="title" placeholder="example.ru" value="{{ $project->title }}">
                    </div>

                    <div class="form-group row">
                        <label for="offer" class="col_form-label">
                            Бюджет
                        </label>

                        <input type="text" name="offer" class="form-control" id="offer" placeholder="100 000" value="{{ $project->offer }}">
                    </div>

                    <div class="form-group row">
                        <label for="client" class="col_form-label">
                            Клиент
                        </label>

                        <input type="text" name="client" class="form-control" id="client" placeholder="ООО 'Рога и Копыта'" value="{{ $project->getClientFormat() }}" autocomplete="off">

                        <div id="client-list" class="client__list"></div>
                    </div>

                    <div class="form-group row">
                        <label for="description" class="col_form-label">
                            Описание
                        </label>

                        <textarea name="description" class="form-control __textarea" id="description" rows="20">{{ $project->description }}</textarea>
                    </div>

                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" name="save" class="btn btn-alt-primary">
                                Сохранить
                            </button>

                            <button type="submit" name="apply" class="btn btn-alt-success">
                                Применить
                            </button>

                            <a class="btn btn-alt-danger" href="{{ route('project.index') }}">
                                Отменить
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/index.blade.php
@extends ('layouts.app')

@section ('title', 'Проекты')

@section ('content')
    <div class="projects">
        <div class="projects-control d_flex">
            <div class="col col_6 col_lg-3">
                <a class="projects-control_block __green" href="{{ route('project.create') }}">
                    <div class="projects-control_block-content_full">
                        <i class="fa fa-plus"></i>
                    </div>

                    <div class="projects-control_block-content_short">
                        Добавить проект
                    </div>
                </a>
            </div>
        </div>

        <div class="projects-content">
            <div class="projects-content_header">
                <h1>Проекты</h1>
            </div>

            <div class="projects-content-block">
                <form class="projects-content-block-search" action="?" method="GET">
                    <div class="form-group">
                        <div class="input-group">
                            <label for="products-search" class="form-label"><span>Поиск:</span>
                                <input type="search" class="form-control projects-content-block-search__input" id="projects-search" name="projects_search" placeholder="Поиск проекта" autocomplete="off" value="{{ $filter }}">
                            </label>

                            <button class="projects-content-block-search__btn" type="submit" title="Поиск">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>

                <div class="table-responsive">
                    <table class="table table-borderless table-striped table-vcenter">
                        <thead>
                            <tr>
                                <th class="text-center">
                                    ID
                                </th>

                                <th>
                                    Проект
                                </th>

                                <th class="text-right">
                                    Бюджет
                                </th>

                                <th class="text-right">
                                    Клиент
                                </th>

                                <th class="text-center">
                                    Дата добавления
                                </th>

                                <th>
                                    Статус
                                </th>

                                <th class="text-center" style="font-size: 18px;">
                                    <i class="fas fa-cogs"></i>
                                </th>
                            </tr>
                        </thead>

                        <tbody>
                        @foreach($projects as $item)
                            <tr>
                                <td class="text-center">
                                    <a href="{{ route('project.edit', $item) }}">
                                        <strong>
                                            {{ $item->id }}
                                        </strong>
                                    </a>
                                </td>

                                <td>
                                    <a href="{{ route('project.edit', $item) }}">
                                        {{ $item->title }}
                                    </a>
                                </td>

                                <td class="text-right __price">
                                    {{ $item->getBudgetFormat() }}
                                </td>

                                <td class="text-right">
                                    {{ $item->getClientNoFormat() }}
                                </td>

                                <td class="text-center">
                                    {{ $item->created_at->format('d.m.Y') }}
                                </td>

                                <td>
                                    @if ($item->isActive())
                                        <span class="badge badge-success">
                                            Активный
                                        </span>
                                    @elseif ($item->isCompleted())
                                        <span class="badge badge-primary">
                                            Завершен
                                        </span>
                                    @elseif ($item->isCancelled())
                                        <span class="badge badge-danger">
                                            Отменен
                                        </span>
                                    @endif
                                </td>

                                <td class="__settings text-center d_flex grid_center">
                                    <a class="btn btn-alt-primary" href="{{ route('project.show', $item) }}">
                                        <i class="fa fa-fw fa-eye"></i>
                                    </a>

                                    <a class="btn btn-alt-primary" href="{{ route('project.edit', $item) }}">
                                        <i class="fas fa-pencil-alt"></i>
                                    </a>

                                    <form method="post" action="{{ route('project.destroy', $item) }}">
                                        @csrf
                                        @method('DELETE')

                                        <button class="btn btn-alt-primary">
                                            <i class="fa fa-fw fa-times"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>

                <nav aria-label="Navigation">
                    {{ $projects->withQueryString()->links() }}
                </nav>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>
        {{ config('app.name') }} - @yield('title')
    </title>

    <link rel="shortcut icon" href="/build/images/favicon.png">

    <link rel="stylesheet" href="/build/css/screen.css">
</head>
<body class="home">

    <main class="main">
        @include('layouts.partials.flash')

        @yield('content')
    </main>


    <script src="/build/js/main.js"></script>
</body>
</html>

resources/views/layouts/partials/flash.blade.php
@if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
@endif

@if (session('success'))
    <div class="alert alert-success" role="alert">
        {{ session('success') }}
    </div>
@endif

@if (session('error'))
    <div class="alert alert-danger" role="alert">
        {{ session('error') }}
    </div>
@endif

@if (session('info'))
    <div class="alert alert-info" role="alert">
        {{ session('status') }}
    </div>
@endif

resources/views/show.blade.php
@extends ('layouts.app')

@section ('title', 'Проект -' . $project->title)

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="projects">
        <div class="projects-content">
            <div class="projects-content_header">
                <h1>Проект - {{ $project->title }}</h1>
            </div>

            <div class="projects-content-block">

                <div class="projects-content__prop">
                    Статус:
                    @if ($project->isActive())
                        <span class="badge badge-success">
                            Активный
                        </span>
                    @elseif ($project->isCompleted())
                        <span class="badge badge-primary">
                            Завершен
                        </span>
                    @elseif ($project->isCancelled())
                        <span class="badge badge-danger">
                            Отменен
                        </span>
                    @endif
                </div>

                <div class="projects-content__prop">
                    Бюджет: <span class="__price">{{ $project->getBudgetFormat() }}</span>
                </div>

                <div class="projects-content__prop">
                    Клиент:  {{ $project->getClientNoFormat() }}
                </div>

                <div class="projects-content__prop">
                    Описание:
                    <div class="projects-content__description">
                        {{ $project->description }}
                    </div>
                </div>

                <div class="projects-content__prop">
                    <a class="btn btn-alt-primary" href="{{ route('project.edit', $project) }}">
                        Редактировать
                    </a>

                    <a class="btn btn-alt-danger" href="{{ route('project.index') }}">
                        Назад
                    </a>
                </div>
            </div>
        </div>
    </div>
@endsection